sudo: required
env:
  matrix:
  - WINEHQ_VERSION=winehq-stable
  - WINEHQ_VERSION=winehq-staging
  - WINEHQ_VERSION=winehq-devel
before_install:
- apt-cache policy wine
- wget -nc https://dl.winehq.org/wine-builds/Release.key
- sudo apt-key add Release.key
- sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
- cat /etc/apt/sources.list
- sudo apt-get update
- sudo apt-get install --install-recommends $WINEHQ_VERSION
script:
- apt-cache policy wine $WINEHQ_VERSION
