sudo: required
addons:
  apt:
    sources:
    # - ubuntu-toolchain-r-test
    # - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/'
    #   key_url: 'https://dl.winehq.org/wine-builds/Release.key'
    # - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ trusty main'
    #  key_url: 'https://dl.winehq.org/wine-builds/Release.key'
    packages:
    # - wine #
    # - gcc-4.9
    # as requested by configure
before_install:
- apt-cache policy wine
install:
- wget -nc https://dl.winehq.org/wine-builds/Release.key
- sudo apt-key add Release.key
- sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
- cat /etc/apt/sources.list
- sudo apt-get update
- sudo apt-get install --install-recommends winehq-stable
script:
- apt-cache policy wine winehq-stable
- true
